### ISSUE TITLE
Add multibot support

### ISSUE THREAD

**Issue by wanderingconfused** [OpenPoGo/OpenPoGoUI#13]
The new UI is nice and I appreciate  the work.  I would like to see all my bots.

**Comment by niicojs** [comment]
From an UI perspective, you can launch it with http://openpogoui.nicontoso.eu?websocket=http;://localhost:8000 for the first, http://openpogoui.nicontoso.eu?websocket=http;://localhost:8001 for the second, etc...
However, you'll need to configure manually the but port for each instance of the bot

**Comment by wanderingconfused** [comment]
Is there a flag for changing the socket port? Should I request that in the OpenPoGoBot issues?

**Comment by niicojs** [comment]
there is no flag. you can try to request it but it will probably be easier to modify it yourself

**Comment by wchill** [comment]
This flag will be added to the bot eventually, but it is not a high priority at the moment.

**Comment by wanderingconfused** [comment]
Sorry if I am being a nuisance. I assume I am changing 
`socketio.run(app, host="0.0.0.0", port=8000, debug=False, use_reloader=False, log_output=False)`
in plugins\socket__init__.py.

**Comment by niicojs** [comment]
Seems correct
