### ISSUE TITLE
Current version does not find app.css on startup

### ISSUE THREAD

**Issue by OhJayGee** [OpenPoGo/OpenPoGoUI#18]
Error: Browser does not find app.css on startup 
Fix: 
server.js line6: 
change from: 
app.use(express.static(__dirname + "/src"));
to:
app.use(express.static(__dirname + "/build"));

**Comment by niicojs** [comment]
If you're a user, just go to http://openpogoui.nicontoso.eu.
If you're a développer you can either run gulp dev-styles to generate CSS file or type gulp watch to automatically generate CSS file when you modify scss.

**Comment by OhJayGee** [comment]
didn't know about gulp dev-styles, nice thanks. I normally just run 'npm install' and 'gulp' on a new pull.

**Comment by niicojs** [comment]
Faire enough I'll add the case generation to default task

**Comment by niicojs** [comment]
CSS génération
