### ISSUE TITLE
Manual destination reaced, bot stops

### ISSUE THREAD

**Issue by SimoneCattozzi** [OpenPoGo/OpenPoGoUI#26]
When manual destination is reaced bot do not restart automatic fort visit but it stops on manual location.

Extra feature request
Draw on map a waypoint path by clicking on pokestops.

**Comment by niicojs** [comment]
Could you share bot log?

**Comment by SimoneCattozzi** [comment]
Emm now the problem is gone. I've killed & restated the Bot and it recalculate correctly next destination based on pokestops after reaching manual destination.

Sorry

**Comment by niicojs** [comment]
OK. If you see it again try to get me as much info as you can. Starting with console log.
Also bot sometimes takes time to restart walking is there is pokestop, pokemon, lure, etc...
