### ISSUE TITLE
Uncaught TypeError: Cannot read property 'send' of undefined

### ISSUE THREAD

**Issue by hanseartic** [OpenPoGo/OpenPoGoUI#3]
When clicking one of the icons (ball, eggs, inventory) in **OpenPoGoUI** nothing happens but the following error-message is shown in JS-console:

```
Uncaught TypeError: Cannot read property 'send' of undefined app.js:12
```

It seems that the `global.ws` property does not get set properly.

**Comment by niicojs** [comment]
could you check again with this url: http://openui.nicontoso.eu (dev env)?

**Comment by hanseartic** [comment]
That's at least giving me log messages:

```
[2016-08-09 17:29:11] Web UI action: Pokemon List
[2016-08-09 17:29:13] Web UI action: Eggs List
[2016-08-09 17:29:14] Web UI action: Inventory List
```

~~But in the UI nothing pops up~~

**Comment by niicojs** [comment]
Could you also share your brower log?

**Comment by hanseartic** [comment]
I got this on branch _master_

```
config.js:53 Load config from storage
jquery-3.1.0.min.js:4 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
socket.js:13 Connecting to ws://localhost:8000
socket.js:24 Connected to Bot
socket.js:29 bot_initialized
app.js:12 Uncaught TypeError: Cannot read property 'send' of undefined
```

I guess you just have not pushed the latest changes you have already running on http://openui.nicontoso.eu to github.

**Comment by hanseartic** [comment]
Checked out _gh-pages_ -- now it works. I was assuming, that master was the newest branch.
I think, this can be closed.

**Comment by niicojs** [comment]
You should not play with source unless you want to contribute.
Always connect to the url to use the gui.
For now the url is http://openpogoui.nicontoso.eu.

I should remove master so it's more clear.
