### ISSUE TITLE
Not working on safari iphone 6 ios 9

### ISSUE THREAD

**Issue by maithanhtan** [OpenPoGo/OpenPoGoUI#6]
Hi the web not working on my iphone. Try to click setting but do not show anything

**Comment by OhJayGee** [comment]
Steps to make UI work on all non ES6 browsers: 
cd OpenPoGoUI
echo '{ "presets": ["es2015"] }' > .babelrc 
mv scripts scripts.es6
babel scripts.es6 --out-dir scripts  

that translates all the es6 scripts to es2015 - then just start node: 
node server.js 
and then on iPhone: use safari to point to http://<yourmachine>:8080/, select the config icon (bottom right) and set the web socket host to http://<yourmachine>:8000, with <yourmachine> being the ipaddress or name of the machine running the web socket server.

Recommendation: 
in ./scripts/config.js line 18: set the websocket: "http://localhost:8000/" to be a host variable set by the build.

**Comment by niicojs** [comment]
by the way, I've made a gulp task that create a minified babelified vesion to deploy. it just hasn't hit production yet :)

**Comment by niicojs** [comment]
also, about the config.js, just hit : http://openui.nicontoso.eu?websocket=http://machine:8000 it will do it for you
(url for dev, will be replaced by the real one soon)

**Comment by OhJayGee** [comment]
Very nice - I was just about to write that you can have gulp do the babel-ization :) 
Thanks for the URL param. And btw: really nice work on the UI - Thank you!

**Comment by niicojs** [comment]
I'll push it into git today

**Comment by maithanhtan** [comment]
I try it but still got the same issue on my phone. Still that some javascript is blocked on IOS. My ipad have the same issue

**Comment by Rlewisrlou666** [comment]
Will this work on iCloud tab sharing?

**Comment by niicojs** [comment]
Could you try it again it should be better but nor tested.
Don't know about tab sharing I don't own a Mac.

**Comment by Rlewisrlou666** [comment]
It just says connecting to bot

**Comment by Rlewisrlou666** [comment]
![image](https://cloud.githubusercontent.com/assets/20677921/17642789/0e648d10-614c-11e6-9157-caa8670367f8.png)

**Comment by niicojs** [comment]
If you could take a look at http://openui.nicontoso.eu.
Did not really work on iphone compatibility but I changed something that could help.
Also, it may be easy to directly access http://openui.nicontoso.eu?websocket=http://bothostname:8000 to connect directly to the bot without having to go to settings.

**Comment by OhJayGee** [comment]
I can confirm that this works on mobile safari on IOS 9.3.3 and IOS 9.3.4 on both iphone and iPad. Note that if you use  http://openui.nicontoso.eu you get a green screen trying to connect to bot.  The bot machine needs to be network accessible by the device showing the map. If you are at home that's easy, if you want the map to work while out and about with your device, then you have to make the bot machine internet accessible (open port forwarding in your home firewall for port 8000 to the bot machine). 
![img_2974](https://cloud.githubusercontent.com/assets/20964478/17648193/325fc2b8-620d-11e6-98f2-1cd8d7bad034.png)

**Comment by niicojs** [comment]
Level 42???

**Comment by OhJayGee** [comment]
Regarding icloud tab sharing and handoff: both work - still your mobile device will need to be able to establish a network connecting with the machine you are running the bot on.

**Comment by OhJayGee** [comment]
And the Lvl42 is a joke - nice work spotting that - I didn't want my account and measly level to be public on a screenshot :)

**Comment by maithanhtan** [comment]
http://openui.nicontoso.eu/ --> site not found can you please help

**Comment by niicojs** [comment]
Should be fixed sorry.
