### ISSUE TITLE
Contributing?

### ISSUE THREAD

**Issue by lifeiscontent** [OpenPoGo/OpenPoGoUI#9]
I was thinking of working on some possible new features of this UI. Which branch should I work out of? It looks like gh-pages, master and the original fork all have recent changes.

**Comment by niicojs** [comment]
yes, it's not very good at the moment.
in theory, I would say contribute on master through PR and we'll push to gh-pages later (=production).

the reality is I'm the only one working on it now and I'm working through https://github.com/nicoschmitt/openui because it's easier to test.

Would you mind contribute there for now until I figure this out?

**Comment by lifeiscontent** [comment]
@nicoschmitt you got it 👍

**Comment by lifeiscontent** [comment]
@nicoschmitt I'm about to open 2 PRs

**Comment by niicojs** [comment]
Bring it on!

**Comment by lifeiscontent** [comment]
@nicoschmitt would you consider the following?
1. Working strictly in this repo as this is probably the repo that will get the most exposure (e.g. not your initial fork)
2. Working strictly in the master branch and only using gh-pages for static content?

maybe I'm misunderstanding something or you're using your initial fork for staging purposes but. If yes, I'd consider spending some time writing some code to do the following:

| Action | Reason |
| --- | --- |
| Remove all processed assets from master branch. (css, etc) | This will help with merge conflicts |
| Automate build/deploy process | This will help with letting users see the most up-to-date features. |
| Add development/production flags | So that during development we can see all the console.logs when they're helpful |
| Use polyfill.io | To support older browsers |

Let me know what you think of these ideas.

**Comment by niicojs** [comment]
could you come to slack to discuss this?

**Comment by lifeiscontent** [comment]
@nicoschmitt I think I pinged you.
